server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: undertow
  undertow:    
    io-threads: 3
    worker-threads: 100
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:  
    name: db  
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: -1
    removeAbandoned: true
    filters: stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1
    useGlobalDataSourceStat: true
    druidLoginName: chendi
    druidPassword: 123456
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.zhongjian.webserver.pojo
  configLocation: classpath:/mybatis-config.xml
token:
  largeLenth: 2000
  jsonFile: /home/zhongjianmall/json/token.json