server:
  #adress: 127.0.0.1
  port: 8080
  context-path: /zjapp/v1
  undertow:    
    io-threads: 3
    worker-threads: 20
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:  
    name: db
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://116.62.124.54:3308/zjsc?useUnicode=true&characterEncoding=utf-8
    username: dog
    password: zjsc&!
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: -1
    removeAbandoned: true
    filters: stat
    connectionProperties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=1000
    useGlobalDataSourceStat: true
    druidLoginName: zhongjian
    druidPassword: 123456
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.zhongjian.webserver.pojo
  configLocation: classpath:/mybatis-config.xml
token:
  largeLenth: 2000
  jsonFile: /home/www/zhongjianmall/json/token.json
upload:
  catalogue: /home/public/upload/pics/
  httpCatalogue: /upload/pics/
  maxFileSize: 30720KB
  maxRequestSize: 102400KB
malldata:
  vipNeedPay: 3000
  subProxyNeedPay: 50000
  gcNeedPay: 99